# Variables shared across all playbooks in all environments
# ---------------------------------------------------------
# ----------------------------------------------
# Environment-related metadata
# ----------------------------------------------
deploy_environment: "{{ lookup('env', 'ENVIRONMENT') | default('testing') }}"
provision_root: "{{ lookup('env', 'PROVISION_ROOT') }}"


# ----------------------------------------------
# Project metadata
# ----------------------------------------------
project_name: "{{ lookup('env', 'PROJECT_NAME') | default('') }}"
project_namespace: "{{ lookup('env', 'PROJECT_NAMESPACE') | default('') }}"
project_team_name: "{{ lookup('env', 'PROJECT_TEAM_NAME') | default('') }}"
project_title: "{{ lookup('env', 'PROJECT_TITLE') | default('') }}"
project_description: "{{ lookup('env', 'PROJECT_DESCRIPTION') | default('') }}"
project_keywords: "{{ lookup('env', 'PROJECT_KEYWORDS') | default('') }}"
project_author: "{{ lookup('env', 'PROJECT_AUTHOR') | default('Parag M. <admin@bitsofparag.com>') }}"
project_author_email: "{{ lookup('env', 'PROJECT_AUTHOR_EMAIL') | default('admin@bitsofparag.com') }}"
project_git_providers: "{{ lookup('env', 'PROJECT_GIT_PROVIDERS') | default(['gitlab_hosted']) }}"
project_license: "{{ lookup('env', 'PROJECT_LICENSE') | default('MIT') }}"
project_privacy: "{{ lookup('env', 'PROJECT_PRIVACY') | default('private') }}"
# Overrides
project_domain_name: "{{ lookup('env', 'DOMAIN_NAME') | default('') }}"


# ----------------------------------------------
# Domain and DNS metadata
# ----------------------------------------------
domain_name: "{{ lookup('env', 'DOMAIN_NAME') | default('') }}"


# ----------------------------------------------
# Gitlab metadata
# ----------------------------------------------
gitlab_group_name: "{{ lookup('env', 'GITLAB_GROUP_NAME') | default('') }}"
gitlab_group_id: "{{ lookup('env', 'GITLAB_GROUP_ID') }}"
gitlab_group_description: "{{ lookup('env', 'GITLAB_GROUP_DESCRIPTION') | default('') }}"
gitlab_skip_group_tasks: false
gitlab_user_access_token: "{{ lookup('env', 'GITLAB_USER_ACCESS_TOKEN') }}"
# Overrides
gitlab_project_labels: "{{ lookup('file', lookup('env', 'PWD') + '/group_vars/gitlab_labels.json') | from_json }}"
gitlab_group_labels: "{{ lookup('file', lookup('env', 'PWD') + '/group_vars/gitlab_labels.json') | from_json }}"
gitlab_privacy: "{{ lookup('env', 'PROJECT_PRIVACY') | default('private') }}"
gitlab_set_dev_branch: true


# ----------------------------------------------
# Github metadata
# ----------------------------------------------
github_user_access_token: "{{ lookup('env', 'GITHUB_USER_ACCESS_TOKEN') }}"


# ----------------------------------------------
# Ops user metadata
# ----------------------------------------------
ops_email: "{{ lookup('env', 'OPS_EMAIL') | default('janedoe@example.com') }}"
ops_user: "{{ lookup('env', 'OPS_USER') | default('ops') }}"
ops_password: "{{ lookup('env', 'OPS_PASSWORD') }}"


# ----------------------------------------------
# AWS secrets
# ----------------------------------------------
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"


# ----------------------------------------------
# Package versions
# ----------------------------------------------
docker_compose_version: "{{ lookup('env', 'DOCKER_COMPOSE_VERSION') | default('1.29.2') }}"
nginx_version: "{{ lookup('env', 'NGINX_VERSION') | default('1.21.0') }}"
nodejs_version: "{{ lookup('env', 'NODEJS_VERSION') | default('14.x') }}"
python_version: "{{ lookup('env', 'PYTHON_VERSION') | default('3.8') }}"
nomad_version: "{{ lookup('env', 'NOMAD_VERSION') | default('1.1.2') }}"
postgresql_version: "{{ lookup('env', 'POSTGRESQL_VERSION') | default('13') }}"


# ----------------------------------------------
# SSH keys
# ----------------------------------------------
user_key_title: ""
user_key_file: ""
