---

- name: Main* Provisioning machine images
  hosts: packer
  roles:
    - user
    - hostnames

- name: Main* Preparing a new project
  hosts: adminpc
  roles:
    - gitlab
    - tfcloud
    - sentry
    - papertrail
