---
# tasks file for roles/internal/tfc

- name: Tfc* GET list of organizations
  when: tfc_org_name is defined and tfc_org_name != ""
  uri:
    url: https://app.terraform.io/api/v2/organizations
    method: GET
    headers:
      Authorization: "Bearer: {{ tfc_token }}"
      Content-Type: "application/vnd.api+json"
    status_code: 200
  register: org_list
  tags:
    - tfc_org_new
    - tfc_org_remove
    - tfc_org_edit
    - tfc_org_debug

- name: Tfc* CREATE an organization "{{ tfc_org_name }}"
  when: tfc_org_name is defined and tfc_org_name != ""
  uri:
    url: https://app.terraform.io/api/v2/organizations
    method: POST
    headers:
      Authorization: "Bearer: {{ tfc_token }}"
      Content-Type: "application/vnd.api+json"
    body: "{{ _tfc_org_json_body }}"
    body_format: 'json'
    status_code: 200
  tags:
    - tfc_org_new
    - tfc_org_remove
    - tfc_org_edit
    - tfc_org_debug
