---
# tasks file for roles/internal/tfc (manage oauth clients)
# References:
# 1. https://www.terraform.io/docs/cloud/api/index.html#authentication
# 2. https://www.terraform.io/docs/cloud/api/oauth-clients.html
# 3. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
# 4. https://docs.ansible.com/ansible/latest/modules/set_fact_module.html#examples

- name: Tfc* INCLUDE TASKS set-facts needed for managing oauth clients
  include_tasks:
    file: "{{playbook_dir}}/../roles/internal/tfcloud/tasks/set-facts.yml"
    apply:
      tags:
        - tfc_oauth_new
        - tfc_oauth_remove
  tags:
    - tfc_oauth_new
    - tfc_oauth_remove


- name: Tfc* SET_FACT variables for oauth template used in POST body for oauth client creation
  when: project_git_provider == "gitlab_hosted"
  set_fact:
    cacheable: yes
    project_git_provider_api_url: "https://{{project_git_provider_domain}}/api/v4"
    project_git_provider_access_token: "{{gitlab_user_access_token}}"
  tags:
    - tfc_oauth_new
    - tfc_oauth_remove


- name: Tfc* CREATE an oauth client
  uri:
    url: "https://app.terraform.io/api/v2/organizations/{{ tfc_org_name }}/oauth-clients"
    method: POST
    headers:
      Authorization: "Bearer {{ tfc_token }}"
      Content-Type: application/vnd.api+json
      Accept: application/json
    body: "{{ tfc_oauth_client_template }}"
    body_format: 'json'
    status_code: 201
    return_content: yes
  register: response
  tags:
    - tfc_oauth_new


- name: Tfc* REMOVE a user-provided oauth client
  when: tfc_oauth_client_id != ""
  uri:
    url: "https://app.terraform.io/api/v2/oauth-clients/{{ tfc_oauth_client_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tfc_token }}"
      Content-Type: application/vnd.api+json
      Accept: application/json
    status_code: [204, 404]
    return_content: yes
  register: response
  tags:
    - tfc_oauth_remove


- name: Tfc* REMOVE the default oauth client
  when: oauth_client_id is defined and oauth_client_id != ""
  uri:
    url: "https://app.terraform.io/api/v2/oauth-clients/{{ oauth_client_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tfc_token }}"
      Content-Type: application/vnd.api+json
      Accept: application/json
    status_code: [204, 404]
    return_content: yes
  register: response
  tags:
    - tfc_oauth_remove
