---
# tasks file for roles/internal/tfc (manage oauth clients)
# References:
# 1. https://www.terraform.io/docs/cloud/api/index.html#authentication
# 2. https://www.terraform.io/docs/cloud/api/oauth-clients.html
# 3. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
# 4. https://docs.ansible.com/ansible/latest/modules/set_fact_module.html#examples

- name: Tfc* INCLUDE TASKS set-facts needed for managing oauth clients
  include_role:
    name: tfcloud
    tasks_from: set-facts
    apply:
      tags:
        - tfc_oauth_new
        - tfc_oauth_remove
  tags:
    - tfc_oauth_new
    - tfc_oauth_remove


- name: Tfc* INCLUDE TASK create oauth_clients for git providers
  when: project_git_providers|length > 0
  include_tasks: oauth-client.yml
  loop: "{{project_git_providers}}"
  tags:
    - tfc_oauth_new


- name: Tfc* INCLUDE TASK remove oauth_clients
  when: oauth_client_list|length > 0
  include_tasks: oauth-client.yml
  loop: "{{oauth_client_list}}"
  tags:
    - tfc_oauth_remove
