---
# tasks file for roles/internal/tfc (manage organizations)
# References:
# 1. https://www.terraform.io/docs/cloud/api/index.html#authentication
# 2. https://www.terraform.io/docs/cloud/api/organizations.html
# 3. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
# 4. https://docs.ansible.com/ansible/latest/modules/set_fact_module.html#examples

- name: Tfc* INCLUDE TASKS set-facts needed for managing organizations
  include_tasks:
    file: "{{playbook_dir}}/../roles/internal/tfcloud/tasks/set-facts.yml"
    apply:
      tags:
        - tfc_org_new
        - tfc_org_remove
  tags:
    - tfc_org_new
    - tfc_org_remove


- name: Tfc* CREATE an organization "{{ tfc_org_name }}"
  when: tfc_org_name is defined and tfc_org_name != ""
  uri:
    url: "https://app.terraform.io/api/v2/organizations"
    method: POST
    headers:
      Authorization: "Bearer {{ tfc_token }}"
      Content-Type: application/vnd.api+json
      Accept: application/json
    body: "{{ tfc_org_template }}"
    return_content: yes
    status_code: 201
  register: response
  tags:
    - tfc_org_new

- name: Tfc* REMOVE organization {{ tfc_org_name }}
  when: tfc_org_name is defined and tfc_org_name != ""
  uri:
    url: "https://app.terraform.io/api/v2/organizations/{{ tfc_org_name }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tfc_token }}"
      Content-Type: application/vnd.api+json
      Accept: application/json
    status_code: [204, 404]
  register: response
  tags:
    - tfc_org_remove
