---
# Tasks for managing users, for e.g ops user
# References:
# 1. https://docs.ansible.com/ansible/2.5/modules/user_module.html

- name: User* CHECK the ops user already exists
  command: grep {{ ops_user }} /etc/passwd
  register: ops_user_exists
  ignore_errors: true
  changed_when: false
  become: true
  tags:
    - user_new
    - user_debug


- name: User* CREATE group {{ ops_user }}
  group: name={{ ops_user }}
  become: true
  tags:
    - user_new


# sudo usermod -aG docker "{{ ops_user }}"
- name: User* CREATE user {{ ops_user }} and add to some default groups
  user:
    name: "{{ ops_user }}"
    group: "{{ ops_user }}"
    groups:
      - docker
      - sudo
      - www-data
    append: true
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ ops_user }}"
    password: "{{ lookup('password', '/tmp/ops_password chars=ascii_letters,digits,punctuation') }}"
    priv: "{{ client }}_{{ tier }}_{{ role }}.*:ALL"
  become: true
  tags:
    - user_new


- name: User* ADD {{ops_user}} to sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ ops_user }}
    owner: root
    mode: 0440
  become: true
  tags:
    - user_new


- name: User* Ensure ssh keys for the {{ops_user}} are up to date
  authorized_key:
    user: "{{ ops_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/' + ops_user + '-shared.pub') }}"
  become: true
  tags:
    - user_keys
    - user_new

# TODO add ssh_configs

- name: User* RESTART SSH service
  service:
    name: ssh
    state: restarted
  become: true
  tags:
    - user_keys
    - user_new
