---
# tasks file for roles/internal/gitlab
#
# Alternate way to include role files would be:
#
# - name: Gitlab* INCLUDE role for new gitlab project or group and its labels
#   when: project_name != "" or gitlab_group_name != ""
#   include_role:
#     name: gitlab
#     tasks_from: new
#     apply:
#       tags:
#         - gitlab_new
#   tags:
#     - gitlab_new

- include: new.yml
- include: edit.yml
- include: remove.yml
